### PR TITLE
Fix crash on space/toggle select with no item

### PR DESCRIPTION
**Pull request by matt-coles**
Should address the TODO that was on line#38 of main.js

### CODE REVIEW

**Comment by golbin** [comment]
Thanks @Alpha-Atom 

But, I think it's better the below codes will be after line 39(the first line in the toggle function) instead of making new blocks.

``` js
if (this.selected === undefined) { // or !_.isNumber(this.selected)
  return;
}
```

What do you think? :-)

**Comment by matt-coles** [comment]
I can't say that I'd see any particular improvements in terms of performance or anything - feel free to enlighten me though :)

That said, it's your project so, refactored as you specified.

**Comment by matt-coles** [comment]
Gonna close this for a minute, I didn't fully test this solution.

**Comment by matt-coles** [comment]
Reopened now with proper testing, apologies for the poor initial effort.

**Comment by golbin** [comment]
@Alpha-Atom Thanks for good patch. And BTW, I think that codes make to read and refactor easy. :-)

**Pull request closed without merging**
