### PR TITLE
A shot at #35

### PR DESCRIPTION
**Pull request by jzsfkzm**
Hey @golbin, here's something for the configurable key mappings, what do you think about it? Should I go ahead in this direction? It's not something you should pull right now, but I wanted to ask your opinion before proceeding.
Things changed: turned the JSON files of view styles into real JS files and we call them with config passed, a JSON containing keyboard mappings. We also use that config in controllers to map keys to specific methods. Users can choose between predefined vi-style and mc-style key mapping.
Custom key mapping is TBD.

### CODE REVIEW

**Comment by golbin** [comment]
@jzsfkzm It's Great! Your patch is almost same as my plan.

But one more feature is needed that is to make using user's own config file. I mean, user can use config file like "~/.git-commander.json" and it contain whole key settings like your vi.json or mc.json.

Could you plz make this? :smiley:

**Comment by jzsfkzm** [comment]
Sure, that's my plan! Great to hear back, I'll go ahead with this then and include a solution for user-defined custom keys mappings.

**Comment by golbin** [comment]
Cool! :+1:

**Comment by jzsfkzm** [comment]
Hello, @golbin, I think I just finished this for now. This is how it works:

There are two config files in `config/key`, `mc.json` and `vi.json`. Both files are containing the same JSON data except they point to different key combos.
One of these files are read as key config. It's `vi.json` by default now.
If you want to use mc.json, you'll need a file under `~/.config/git-commander/config.json` containing a key called `keySet`, with the value `mc`.
Also, you can place a key called `keys` in this file, cloning parts or the whole of key config and setting your own keys.
If you think it's ok, I'll add these to the README.md with examples and such.

**Comment by golbin** [comment]
@jzsfkzm Great! Please update the README.md

And what do you think about you'll be a contributor of this project? :smiley: If you want, please make a contributor section in the README.md and I'll add you as a collaborator of this repo.

**Comment by jzsfkzm** [comment]
@golbin I just added the docs to README.md
I would happily help as a collaborator in the repo, but not sure if a _Contributors_ block is needed in the README.md - as I see, anyone changing even one line of the code is a contributor, and all their work is visible in the Git history. I wouldn't mind maintaining such an information manually. Anyway, it's up to you.

**Comment by golbin** [comment]
@jzsfkzm Thanks for the update.

And sometimes when I have issues for some projects and need a fast feedback and if there is no contributor section, I'm in a deadlock because I don't know who can manage the repo.

But the contributor section is not required as you said. And for now, we don't need to have the section. So I'll just add you as a collaborator. Thanks! :smile:

**Comment by golbin** [comment]
@jzsfkzm one more thing, do you have a account on npmjs.com? I'll add you as a collaborator to npmjs too.

**Pull request merged**
